mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),

    url(r'^', include('todolist.urls', namespace='todolist')),
]

todolist/urls.py
from django.conf.urls import url

from todolist.views import ToDoListLV, ToDoListCal, SearchFormView, ToDolistCreate, ToDolistUpdate, ToDolistDelete
app_name = 'todolist'

urlpatterns = [
    url(r'^$', ToDoListLV.as_view(), name='index'),
    url(r'^calendar$', ToDoListCal.as_view(), name='calendar'),
    url(r'^search/$',SearchFormView.as_view(), name='search'),
    url(r'^create/$',ToDolistCreate.as_view(), name='create'),
    #url(r'^update/(?P<pk>\s+)$',ToDolistUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$',ToDolistDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/update/$', ToDolistUpdate.as_view(), name='update')
]

todolist/models.py
from django.db import models
from datetime import datetime

from django.contrib.auth.models import User
# Create your models here.


class ToDoList(models.Model):
    title = models.CharField('TITLE', max_length=50)
    content = models.TextField('CONTENT', max_length=100, blank=True, help_text='simple content text.')
    start_date = models.DateTimeField('Start Date')
    end_date = models.DateTimeField('End Date')
    owner = models.ForeignKey(User, null=True, on_delete=True)

    def __str__(self):
        return self.title

todolist/forms.py
from django import forms
from todolist.models import ToDoList


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')


class CreateForm(forms.ModelForm):
	class Meta:
		model = ToDoList
		fields = ['title', 'content', 'start_date', 'end_date']
		widgets = {
			'title': forms.TextInput(attrs={
				'class': 'form-control'
			}),
			'content': forms.Textarea(attrs={
				'class': 'form-control'
			}),
			'start_date': forms.DateInput(attrs={
				'class': 'form-control col-md-4',
				'placeholder': 'year-mm-dd 형식으로 입력'
			}),
			'end_date': forms.DateInput(attrs={
				'class': 'form-control col-md-4',
				'placeholder': 'year-mm-dd 형식으로 입력'
			}),
		}


class UpdateForm(forms.ModelForm):
	class Meta:
		model = ToDoList
		fields = ['title', 'content', 'start_date', 'end_date']
		widgets = {
			'title': forms.TextInput(attrs={
				'class': 'form-control'
			}),
			'content': forms.Textarea(attrs={
				'class': 'form-control'
			}),
			'start_date': forms.DateInput(attrs={
				'class': 'form-control col-md-4',
				'placeholder': 'year-mm-dd 형식으로 입력'
			}),
			'end_date': forms.DateInput(attrs={
				'class': 'form-control col-md-4',
				'placeholder': 'year-mm-dd 형식으로 입력'
			}),
		}
	# title = forms.CharField(
	# 	label="title",
	# 	widget=forms.TextInput(
	# 		attrs={
	# 			"class": "form-control",
	# 			"placeholder": "title",
	# 		})
	# )
	# content = forms.CharField(
	# 	label="content",
	# 	widget=forms.Textarea(
	# 		attrs={
	# 			"class": "form-control",
	# 			"placeholder": "content",
	# 		})
	# )
	# start_date = forms.DateField(
	# 	label="start Date:",
	# 	widget=forms.DateInput(
	# 		attrs={
	# 			"class": "form-control",
	# 			"placeholder": "start Date"
	# 		}
	# 	)
	# )
	# end_date = forms.DateField(
	# 	label="end Date:",
	# 	widget=forms.DateInput(
	# 		attrs={
	# 			"class": "form-control",
	# 			"placeholder": "end Date"
	# 		}
	# 	)
	# )

mysite/views.py
from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/login.html'

todolist/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy


from todolist.forms import PostSearchForm, CreateForm, UpdateForm
from todolist.models import ToDoList
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin


class ToDoListLV(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    model = ToDoList

    def get_queryset(self):
        queryset = super(ToDoListLV, self).get_queryset()
        return queryset.filter(end_date__gt=datetime.now()).filter(owner=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['today_work'] = super(ToDoListLV, self).get_queryset().filter(end_date__year=datetime.now().year,
                                end_date__month=datetime.now().month,
                                end_date__day=datetime.now().day).filter(owner=self.request.user)
        context['finish_work'] = super(ToDoListLV, self).get_queryset().filter(end_date__lt=datetime.now()).filter(
            owner=self.request.user)

        return context


class ToDoListCal(ListView):
    template_name = 'todolist/todolist_calendar.html'
    model = ToDoList

    def get_queryset(self):
        queryset = super(ToDoListCal, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class Post(object):
    pass


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'todolist/post_search.html'

    def form_vaild(self, form):
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(
            Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['objects_list'] = post_list

        return render(self.request, self.template_name, context)


class ToDolistCreate(LoginRequiredMixin, CreateView):
    form_class = CreateForm
    model = ToDoList
    # fields = ['title', 'content', 'start_date', 'end_date']

    success_url = reverse_lazy('todolist:index')

    def form_valid(self, form):  # 3
        form.instance.owner = self.request.user  # 4
        return super(ToDolistCreate, self).form_valid(form)  # 5


class ToDolistUpdate(LoginRequiredMixin,UpdateView):
    template_name = "todolist/todolist_update.html"
    form_class = UpdateForm
    model = ToDoList
    # fields = ['title', 'content', 'start_date', 'end_date']
    success_url = reverse_lazy('todolist:index')

    def form_valid(self, form):  # 3
        form.instance.owner = self.request.user  # 4
        return super(ToDolistUpdate, self).form_valid(form)  #



class ToDolistDelete(LoginRequiredMixin, DeleteView):
    model = ToDoList
    success_url = reverse_lazy('todolist:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}welcome {% endblock %}</title>

    <!-- Bootstrap core CSS -->
  {% load staticfiles %}

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

  {% block bootstrap %}
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    {% endblock %}

  {% block javascript %}

  {% endblock %}

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="/">To do List</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              {% block nav %}
              {% endblock %}
          </ul>
        </div>
      </div>
    </nav>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

    <!-- Bootstrap core JavaScript -->

  </body>

</html>

todolist/templates/todolist/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<div id="content">

<h1>todolist Search</h1>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" />
</form>

<br/><br/>

{% if object_list %}
{% for post in object_list %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}

</div>
{% endblock %}

todolist/templates/todolist/todolist_calendar.html
{% extends "base.html" %}

{% block title %}To do List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/calendar.css" %}{% endblock %}

{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <link href="{% static "fullcalendar/fullcalendar.min.css" %}" rel="stylesheet">
    <script src="{% static "fullcalendar/fullcalendar.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/calendar.js" %}" type="text/javascript"></script>
{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="/">Main</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="/calendar">Calendar</a>
    </li>
    {% if user.is_active %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{% firstof user.get_short_name user.get_username %}</a>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-12" style="margin: 50px auto;">
            <div id='calendar'></div>
        </div>
    </div>
    <script type="text/javascript">
    $(document).ready(function () {
        const date = new Date();
        let y = date.getFullYear();
        let d = date.getDate();
        let m = date.getMonth();

       const calendar = $('#calendar').fullCalendar({
           selectable: true,
           events: [
               {% for todo in object_list %}
               {
                   textColor: 'white',
                   title: "{{ todo.title }}",
                   start: new Date({{ todo.start_date.year }}, {{ todo.start_date.month }}-1, {{ todo.start_date.day }}),
                   end: new Date({{ todo.end_date.year }}, {{ todo.end_date.month }}-1, {{ todo.end_date.day }}+1)
               },
               {% endfor %}
           ]
       })
    });
    </script>
{% endblock %}

todolist/templates/todolist/todolist_confirm_delete.html
{% extends "base.html" %}

{% block title %}To do List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/todolist_list.css" %}{% endblock %}

{% block nav %}
    <li class="nav-item active">
        <a class="nav-link" href="/">Main</a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="/calendar">Calendar</a>
    </li>
    {% if user.is_active %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{% firstof user.get_short_name user.get_username %}</a>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="col-md-6" style="margin: 50px auto;">

            <h1>Delete "{{ object }}"</h1>
            <form class="form" style="margin: 50px auto;" action="." method="post">{% csrf_token %}
                <p> Are you sure you want to delete "{{ object }}" ?</p>
                <input type="submit" class="btn btn-danger" style="width:70%; height:50px; margin:20px auto;" value="delete" />
            </form>
        </div>
    </div>
{% endblock %}

todolist/templates/todolist/todolist_detail.html
<h1>ToDolist Details</h1>
<h2>Name: {{object.name}}</h2>

todolist/templates/todolist/todolist_form.html
{% extends "base.html" %}

{% block title %}To do List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/todolist_list.css" %}{% endblock %}

{% block nav %}
    <li class="nav-item active">
        <a class="nav-link" href="/">Main</a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="/calendar">Calendar</a>
    </li>
    {% if user.is_active %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{% firstof user.get_short_name user.get_username %}</a>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="col-md-6" style="margin: 50px auto;">
            <h1>To do</h1>
            <form class="form" style="margin: 50px auto;" action="." method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" style="width:70%; height:50px; margin:20px auto;" value="ADD" />
            </form>
        </div>
    </div>
{% endblock %}

todolist/templates/todolist/todolist_update.html
{% extends "base.html" %}

{% block title %}To do List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/todolist_list.css" %}{% endblock %}

{% block nav %}
    <li class="nav-item active">
        <a class="nav-link" href="/">Main</a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="/calendar">Calendar</a>
    </li>
    {% if user.is_active %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{% firstof user.get_short_name user.get_username %}</a>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="col-md-6" style="margin: 50px auto;">
            <h1>To do</h1>
            <form class="form" style="margin: 50px auto;" action="." method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" style="width:70%; height:50px; margin:20px auto;" value="UPDATE" />
            </form>
        </div>
    </div>
{% endblock %}